name: Simulation to Test The ML Models

on:
  push:
  pull_request:

env:
  ZEPHYR_SDK_VERSION: "0.16.8"
  SDK_ROOT: "${{ github.workspace }}/zephyr-sdk"

jobs:
  test_classifier:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci-base:v0.28.8
    strategy:
      matrix:
        MODEL_VERSION: ["v1", "v2", "v3", "v4", "v5"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Zephyr SDK and workspace
        uses: actions/cache@v4
        with:
          path: |
            zephyr-sdk/
            zephyr/
            modules/
            bootloader/
            .west/
          key: zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}-${{ hashFiles('application/west.yml') }}

      - name: Install Zephyr SDK
        run: |
          SDK_DIR="$SDK_ROOT/zephyr-sdk-$ZEPHYR_SDK_VERSION"
          if